In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data/regression/mumbai_houses_task.csv')
#data.drop(['Unnamed: 0'], axis=1, inplace=True)
display(df)
s=pd.get_dummies(df)
s.to_csv('data/regression/one-hot_encoded_mumbai_houses_task.csv', index=False)
df = pd.read_csv('data/regression/one-hot_encoded_mumbai_houses_task.csv')
display(df)



price    area   latitude  longitude  Bedrooms  Bathrooms  Balcony  \
0     22400000.0   629.0  19.032800  72.896357       2.0        2.0      0.0   
1     35000000.0   974.0  19.032800  72.896357       3.0        2.0      0.0   
2     31700000.0   968.0  19.085600  72.909277       3.0        3.0      0.0   
3     18700000.0   629.0  19.155756  72.846862       2.0        2.0      2.0   
4     13500000.0  1090.0  19.177555  72.849887       2.0        2.0      0.0   
...          ...     ...        ...        ...       ...        ...      ...   
6250  19500000.0   810.0  19.138320  72.810020       2.0        2.0      0.0   
6251  22000000.0  1400.0  19.221920  72.854250       3.0        3.0      1.0   
6252  20000000.0   750.0  19.144320  72.824111       2.0        2.0      0.0   
6253  11000000.0   700.0  19.047201  72.872225       2.0        2.0      0.0   
6254  15000000.0   900.0  19.168818  72.936375       2.0        2.0      0.0   

                  Status      neworold  parking Furnished_status  Lift  \
0     Under Construction  New Property      0.0              NaN   0.0   
1     Under Construction  New Property      0.0              NaN   0.0   
2     Under Construction  New Property      0.0              NaN   0.0   
3          Ready to Move  New Property      2.0              NaN   2.0   
4                    NaN  New Property      0.0      Unfurnished   0.0   
...                  ...           ...      ...              ...   ...   
6250       Ready to Move        Resale      0.0   Semi-Furnished   0.0   
6251       Ready to Move        Resale      1.0      Unfurnished   1.0   
6252       Ready to Move        Resale      0.0              NaN   0.0   
6253       Ready to Move        Resale      0.0        Furnished   0.0   
6254       Ready to Move        Resale      0.0              NaN   0.0   

     type_of_building  
0                Flat  
1                Flat  
2                Flat  
3                Flat  
4                Flat  
...               ...  
6250             Flat  
6251             Flat  
6252             Flat  
6253             Flat  
6254             Flat  

[6255 rows x 13 columns]

price    area   latitude  longitude  Bedrooms  Bathrooms  Balcony  \
0     22400000.0   629.0  19.032800  72.896357       2.0        2.0      0.0   
1     35000000.0   974.0  19.032800  72.896357       3.0        2.0      0.0   
2     31700000.0   968.0  19.085600  72.909277       3.0        3.0      0.0   
3     18700000.0   629.0  19.155756  72.846862       2.0        2.0      2.0   
4     13500000.0  1090.0  19.177555  72.849887       2.0        2.0      0.0   
...          ...     ...        ...        ...       ...        ...      ...   
6250  19500000.0   810.0  19.138320  72.810020       2.0        2.0      0.0   
6251  22000000.0  1400.0  19.221920  72.854250       3.0        3.0      1.0   
6252  20000000.0   750.0  19.144320  72.824111       2.0        2.0      0.0   
6253  11000000.0   700.0  19.047201  72.872225       2.0        2.0      0.0   
6254  15000000.0   900.0  19.168818  72.936375       2.0        2.0      0.0   

      parking  Lift  Status_Ready to Move  Status_Under Construction  \
0         0.0   0.0                     0                          1   
1         0.0   0.0                     0                          1   
2         0.0   0.0                     0                          1   
3         2.0   2.0                     1                          0   
4         0.0   0.0                     0                          0   
...       ...   ...                   ...                        ...   
6250      0.0   0.0                     1                          0   
6251      1.0   1.0                     1                          0   
6252      0.0   0.0                     1                          0   
6253      0.0   0.0                     1                          0   
6254      0.0   0.0                     1                          0   

      neworold_New Property  neworold_Resale  Furnished_status_Furnished  \
0                         1                0                           0   
1                         1                0                           0   
2                         1                0                           0   
3                         1                0                           0   
4                         1                0                           0   
...                     ...              ...                         ...   
6250                      0                1                           0   
6251                      0                1                           0   
6252                      0                1                           0   
6253                      0                1                           1   
6254                      0                1                           0   

      Furnished_status_Semi-Furnished  Furnished_status_Unfurnished  \
0                                   0                             0   
1                                   0                             0   
2                                   0                             0   
3                                   0                             0   
4                                   0                             1   
...                               ...                           ...   
6250                                1                             0   
6251                                0                             1   
6252                                0                             0   
6253                                0                             0   
6254                                0                             0   

      type_of_building_Flat  type_of_building_Individual House  
0                         1                                  0  
1                         1                                  0  
2                         1                                  0  
3                         1                                  0  
4                         1                                  0  
...                     ...  

In [3]:

#data = data.fillna(data.mode())
#print(df[['Status', 'Furnished_status']].mode())
#df['Status'] = df['Status']. fillna('Ready to Move')
#df['Furnished_status'] = df['Furnished_status']. fillna('Unfurnished')

print(pd.isnull(df).sum())

price                                0
area                                 0
latitude                             0
longitude                            0
Bedrooms                             0
Bathrooms                            0
Balcony                              0
parking                              0
Lift                                 0
Status_Ready to Move                 0
Status_Under Construction            0
neworold_New Property                0
neworold_Resale                      0
Furnished_status_Furnished           0
Furnished_status_Semi-Furnished      0
Furnished_status_Unfurnished         0
type_of_building_Flat                0
type_of_building_Individual House    0
dtype: int64


In [4]:
y = df["price"]
X = df.drop(["price"], axis=1)
display(y)
display(X)


0       22400000.0
1       35000000.0
2       31700000.0
3       18700000.0
4       13500000.0
           ...    
6250    19500000.0
6251    22000000.0
6252    20000000.0
6253    11000000.0
6254    15000000.0
Name: price, Length: 6255, dtype: float64

area   latitude  longitude  Bedrooms  Bathrooms  Balcony  parking  \
0      629.0  19.032800  72.896357       2.0        2.0      0.0      0.0   
1      974.0  19.032800  72.896357       3.0        2.0      0.0      0.0   
2      968.0  19.085600  72.909277       3.0        3.0      0.0      0.0   
3      629.0  19.155756  72.846862       2.0        2.0      2.0      2.0   
4     1090.0  19.177555  72.849887       2.0        2.0      0.0      0.0   
...      ...        ...        ...       ...        ...      ...      ...   
6250   810.0  19.138320  72.810020       2.0        2.0      0.0      0.0   
6251  1400.0  19.221920  72.854250       3.0        3.0      1.0      1.0   
6252   750.0  19.144320  72.824111       2.0        2.0      0.0      0.0   
6253   700.0  19.047201  72.872225       2.0        2.0      0.0      0.0   
6254   900.0  19.168818  72.936375       2.0        2.0      0.0      0.0   

      Lift  Status_Ready to Move  Status_Under Construction  \
0      0.0                     0                          1   
1      0.0                     0                          1   
2      0.0                     0                          1   
3      2.0                     1                          0   
4      0.0                     0                          0   
...    ...                   ...                        ...   
6250   0.0                     1                          0   
6251   1.0                     1                          0   
6252   0.0                     1                          0   
6253   0.0                     1                          0   
6254   0.0                     1                          0   

      neworold_New Property  neworold_Resale  Furnished_status_Furnished  \
0                         1                0                           0   
1                         1                0                           0   
2                         1                0                           0   
3                         1                0                           0   
4                         1                0                           0   
...                     ...              ...                         ...   
6250                      0                1                           0   
6251                      0                1                           0   
6252                      0                1                           0   
6253                      0                1                           1   
6254                      0                1                           0   

      Furnished_status_Semi-Furnished  Furnished_status_Unfurnished  \
0                                   0                             0   
1                                   0                             0   
2                                   0                             0   
3                                   0                             0   
4                                   0                             1   
...                               ...                           ...   
6250                                1                             0   
6251                                0                             1   
6252                                0                             0   
6253                                0                             0   
6254                                0                             0   

      type_of_building_Flat  type_of_building_Individual House  
0                         1                                  0  
1                         1                                  0  
2                         1                                  0  
3                         1                                  0  
4                         1                                  0  
...                     ...                                ...  
6250                      1                                  0  
6251                      1             

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [6]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((4378, 17), (4378,), (1877, 17), (1877,))

In [7]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge

In [8]:
lr = LinearRegression().fit(X_train, y_train)
for item in zip(X_train.columns, lr.coef_.round()):
    print(item)

lr.predict(X_test)

('area', 22251.0)
('latitude', -82415272.0)
('longitude', -78900839.0)
('Bedrooms', -538667.0)
('Bathrooms', 7724503.0)
('Balcony', -58450.0)
('parking', -58450.0)
('Lift', -58450.0)
('Status_Ready to Move', 2268206.0)
('Status_Under Construction', 3967523.0)
('neworold_New Property', 603553.0)
('neworold_Resale', -603553.0)
('Furnished_status_Furnished', 2017685.0)
('Furnished_status_Semi-Furnished', 181312.0)
('Furnished_status_Unfurnished', -401138.0)
('type_of_building_Flat', 57187.0)
('type_of_building_Individual House', -57187.0)


array([19583176.04738045, 38363744.26920891,  8530044.19365215, ...,
       23842015.15165901, 27432659.92137051, 38578632.54572582])

In [9]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from math import sqrt

In [10]:
y_pred = lr.predict(X_test)
y_pred


array([19583176.04738045, 38363744.26920891,  8530044.19365215, ...,
       23842015.15165901, 27432659.92137051, 38578632.54572582])

In [11]:
def MAE(y_test, y_predict):
    return np.sum(abs(y_test-y_predict))/len(y_test)

def MSE(y_test, y_predict):
    return np.sum((y_test - y_predict)**2) / len(y_test)

def RMSE(y_test, y_predict):
    return sqrt(MSE(y_test, y_predict))

def MAPE(y_test, y_predict):
    return np.mean(abs((y_test - y_predict) / y_test))

def R2(y_test, y_predict):
    return 1 - (MSE(y_test, y_predict) / (np.sum((y_test - y_test.mean())**2) / len(y_test)))

In [12]:
print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, y_pred))}')
import numpy as np


print(f'MAE: {MAE(y_test, y_pred)}')
print(f'MSE: {MSE(y_test, y_pred)}')
print(f'RMSE: {RMSE(y_test, y_pred)}')
print(f'MAPE: {MAPE(y_test, y_pred)}')
print(f'R^2: {R2(y_test, y_pred)}')
print(f'R^2: {lr.score(X_test, y_test)}')


MAE: 9184976.737156762
MSE: 288558278297680.94
RMSE: 16987003.217097502
MAPE: 0.7418448691040338
MAE: 9184976.737156762
MSE: 288558278297680.94
RMSE: 16987003.217097502
MAPE: 0.550333809815981
R^2: 0.6374108811460768
R^2: 0.6374108811460768


In [13]:
len(lr.coef_)
lr.coef_

array([ 2.22506753e+04, -8.24152718e+07, -7.89008392e+07, -5.38667145e+05,
        7.72450285e+06, -5.84501705e+04, -5.84501705e+04, -5.84501705e+04,
        2.26820634e+06,  3.96752291e+06,  6.03552946e+05, -6.03552946e+05,
        2.01768472e+06,  1.81312057e+05, -4.01137840e+05,  5.71866832e+04,
       -5.71866832e+04])

In [14]:
# L1
ridge = Ridge(alpha=0.06).fit(X_train, y_train)
y_pred = ridge.predict(X_test)
print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, y_pred))}')
print(f'R^2: {ridge.score(X_test, y_test)}')
ridge.coef_

MAE: 9180282.576033257
MSE: 288519065317265.6
RMSE: 16985848.972520202
MAPE: 0.7413175213602567
R^2: 0.6374601543816266


array([ 2.22535322e+04, -8.23055488e+07, -7.85573194e+07, -5.40518656e+05,
        7.72905747e+06, -5.90268276e+04, -5.90268276e+04, -5.90268276e+04,
        2.26643302e+06,  3.84862763e+06,  6.03299715e+05, -6.03299715e+05,
        2.02128683e+06,  1.79838888e+05, -4.03278117e+05,  5.88714146e+04,
       -5.88714146e+04])

In [15]:
# L2
lasso = Lasso(alpha=0.4).fit(X_train, y_train)
y_pred = lasso.predict(X_test)
#print(np.mean(abs(y_test-y_pred)))
print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, y_pred))}')
print(f'R^2: {lasso.score(X_test, y_test)}')
lasso.coef_

MAE: 9184975.40113886
MSE: 288558267334087.56
RMSE: 16987002.89439216
MAPE: 0.7418446882042914
R^2: 0.6374108949224262


array([ 2.22506750e+04, -8.24152380e+07, -7.89007114e+07, -5.38663519e+05,
        7.72450115e+06, -1.75351035e+05, -7.97234689e-11, -7.97234689e-11,
        2.26819178e+06,  3.96663333e+06,  1.20710139e+06, -3.21343461e-09,
        2.01768070e+06,  1.81305820e+05, -4.01141765e+05,  1.14368291e+05,
       -2.84130215e-09])

In [16]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
#import numpy as np

In [17]:
parameters = {'alpha': np.arange(0, 1, 0.1)}
ridge_optimal = GridSearchCV(Ridge(), parameters).fit(X_train, y_train)
ridge_optimal.best_params_

{'alpha': 0.30000000000000004}

In [18]:
ridge_optimal = RandomizedSearchCV(Ridge(), parameters).fit(X_train, y_train)
ridge_optimal.best_params_

{'alpha': 0.30000000000000004}

In [19]:
X = X_train.values.reshape(-1,17)
y = y_train.values.reshape(-1,1)

lr = LinearRegression().fit(X, y)
lr.coef_

array([[ 2.22506753e+04, -8.24152718e+07, -7.89008392e+07,
        -5.38667145e+05,  7.72450285e+06, -5.84501705e+04,
        -5.84501705e+04, -5.84501705e+04,  2.26820634e+06,
         3.96752291e+06,  6.03552946e+05, -6.03552946e+05,
         2.01768472e+06,  1.81312057e+05, -4.01137840e+05,
         5.71866832e+04, -5.71866832e+04]])

In [20]:
from sklearn.preprocessing import PolynomialFeatures
# создаем объект, который позволит расширить множество предикторов
pf = PolynomialFeatures(2)
# добавляем новые предикторы
X_p=pf.fit_transform(X) 
X_p

array([[1.00000000e+00, 8.75000000e+02, 1.92099437e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 1.80000000e+03, 1.90563393e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 8.50000000e+02, 1.91982667e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.00000000e+00, 9.85000000e+02, 1.90472012e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 1.20000000e+03, 1.92825709e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 1.54200000e+03, 1.91417142e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [21]:
lr2 = LinearRegression().fit(X_p, y)
lr2.coef_

array([[ 1.22857176e+03,  5.06627909e+06, -1.76002558e+10,
        -1.73411670e+10, -1.63795889e+09,  1.46645967e+09,
         4.08325480e+07,  4.08325508e+07,  4.08325374e+07,
         9.63708844e+08,  3.88661800e+03, -1.16719097e+08,
         1.16719101e+08,  5.13688030e+08,  4.42492911e+08,
         3.18681240e+08,  7.02702199e+07, -7.02699500e+07,
        -9.10516236e-01, -7.63080967e+04, -1.18776062e+05,
         2.11941475e+03,  2.34511433e+01,  1.67065395e+02,
         1.68918048e+02,  1.69187359e+02, -1.79168223e+03,
        -1.18213140e+04,  2.53225810e+06,  2.53149349e+06,
         9.85242145e+03,  3.86818312e+03,  4.49606287e+03,
         2.52937550e+06,  2.53436902e+06,  2.63214637e+07,
         4.70435400e+08,  9.70484754e+05, -2.68883080e+07,
         8.52457327e+05,  8.52457331e+05,  8.52457355e+05,
        -8.31059715e+06,  7.38447857e+04, -8.79531383e+09,
        -8.80494210e+09, -1.10472203e+07, -3.38257755e+06,
         9.49286919e+05, -8.80253735e+09, -8.79771858e+0

In [22]:
X_d = X
y_d = lr2.coef_[0][2] + lr2.coef_[0][1]*X_d + lr2.coef_[0][0]*X_d**2
y_d


array([[-1.22266364e+10, -1.75024795e+10, -1.72247576e+10, ...,
        -1.75951883e+10, -1.75951883e+10, -1.76002558e+10],
       [-4.50038096e+09, -1.75032649e+10, -1.72243041e+10, ...,
        -1.76002558e+10, -1.75951883e+10, -1.76002558e+10],
       [-1.24062755e+10, -1.75025392e+10, -1.72246771e+10, ...,
        -1.76002558e+10, -1.75951883e+10, -1.76002558e+10],
       ...,
       [-1.14179799e+10, -1.75033117e+10, -1.72245406e+10, ...,
        -1.75951883e+10, -1.75951883e+10, -1.76002558e+10],
       [-9.75157759e+09, -1.75021081e+10, -1.72244861e+10, ...,
        -1.76002558e+10, -1.75951883e+10, -1.76002558e+10],
       [-6.86679977e+09, -1.75028284e+10, -1.72247700e+10, ...,
        -1.76002558e+10, -1.75951883e+10, -1.76002558e+10]])

In [23]:
y_pred = lr2.predict(X_p)
print(f'R^2: {R2(y, y_pred)}')
y_pred

R^2: 0.7802953439021896


array([[16539952.69335938],
       [43047757.94970703],
       [16359364.65966797],
       ...,
       [23070665.20947266],
       [14098861.10620117],
       [34224449.30737305]])

In [24]:
parameters = {'alpha': np.arange(0, 1, 0.1)}
ridge_optimal = GridSearchCV(Ridge(), parameters).fit(X_p, y)


D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.4829e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.39902e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.86607e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.74188e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcon

In [25]:
# L1
print(ridge_optimal.best_params_['alpha'])
ridge = Ridge(alpha=ridge_optimal.best_params_['alpha']).fit(X_p, y)
y_pred = ridge.predict(X_p)
#y_pred = y_d
print(f'MAE: {MAE(y, y_pred)}')
print(f'MSE: {MSE(y, y_pred)}')
print(f'RMSE: {RMSE(y, y_pred)}')
print(f'MAPE: {MAPE(y, y_pred)}')
print(f'R^2: {R2(y, y_pred)}')
#ridge.coef_

0.9
MAE: 7502972.386547057
MSE: 179130921426527.28
RMSE: 13383980.029368218
MAPE: 0.3399539071079584
R^2: 0.767278862526942


D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.19501e-17): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T


In [40]:
# L2
lasso = Lasso(alpha=ridge_optimal.best_params_['alpha']).fit(X_p, y)
y_pred = lasso.predict(X_p)

print(f'MAE: {mean_absolute_error(y, y_pred)}')
print(f'MSE: {mean_squared_error(y, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y, y_pred))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y, y_pred))}')
print(f'R^2: {lasso.score(X_p, y)}')
#lasso.coef_

MAE: 8603323.016103134
MSE: 227857342924009.97
RMSE: 15094944.283567594
MAPE: 0.6729914592839061
R^2: 0.7039750613429743


D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.988e+17, tolerance: 3.370e+14
  model = cd_fast.enet_coordinate_descent(
