In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data/regression/mumbai_houses_task.csv')
#data.drop(['Unnamed: 0'], axis=1, inplace=True)
display(df)
s=pd.get_dummies(df)
s.to_csv('data/regression/one-hot_encoded_mumbai_houses_task.csv', index=False)
df = pd.read_csv('data/regression/one-hot_encoded_mumbai_houses_task.csv')
display(df)



price    area   latitude  longitude  Bedrooms  Bathrooms  Balcony  \
0     22400000.0   629.0  19.032800  72.896357       2.0        2.0      0.0   
1     35000000.0   974.0  19.032800  72.896357       3.0        2.0      0.0   
2     31700000.0   968.0  19.085600  72.909277       3.0        3.0      0.0   
3     18700000.0   629.0  19.155756  72.846862       2.0        2.0      2.0   
4     13500000.0  1090.0  19.177555  72.849887       2.0        2.0      0.0   
...          ...     ...        ...        ...       ...        ...      ...   
6250  19500000.0   810.0  19.138320  72.810020       2.0        2.0      0.0   
6251  22000000.0  1400.0  19.221920  72.854250       3.0        3.0      1.0   
6252  20000000.0   750.0  19.144320  72.824111       2.0        2.0      0.0   
6253  11000000.0   700.0  19.047201  72.872225       2.0        2.0      0.0   
6254  15000000.0   900.0  19.168818  72.936375       2.0        2.0      0.0   

                  Status      neworold  parking Furnished_status  Lift  \
0     Under Construction  New Property      0.0              NaN   0.0   
1     Under Construction  New Property      0.0              NaN   0.0   
2     Under Construction  New Property      0.0              NaN   0.0   
3          Ready to Move  New Property      2.0              NaN   2.0   
4                    NaN  New Property      0.0      Unfurnished   0.0   
...                  ...           ...      ...              ...   ...   
6250       Ready to Move        Resale      0.0   Semi-Furnished   0.0   
6251       Ready to Move        Resale      1.0      Unfurnished   1.0   
6252       Ready to Move        Resale      0.0              NaN   0.0   
6253       Ready to Move        Resale      0.0        Furnished   0.0   
6254       Ready to Move        Resale      0.0              NaN   0.0   

     type_of_building  
0                Flat  
1                Flat  
2                Flat  
3                Flat  
4                Flat  
...               ...  
6250             Flat  
6251             Flat  
6252             Flat  
6253             Flat  
6254             Flat  

[6255 rows x 13 columns]

price    area   latitude  longitude  Bedrooms  Bathrooms  Balcony  \
0     22400000.0   629.0  19.032800  72.896357       2.0        2.0      0.0   
1     35000000.0   974.0  19.032800  72.896357       3.0        2.0      0.0   
2     31700000.0   968.0  19.085600  72.909277       3.0        3.0      0.0   
3     18700000.0   629.0  19.155756  72.846862       2.0        2.0      2.0   
4     13500000.0  1090.0  19.177555  72.849887       2.0        2.0      0.0   
...          ...     ...        ...        ...       ...        ...      ...   
6250  19500000.0   810.0  19.138320  72.810020       2.0        2.0      0.0   
6251  22000000.0  1400.0  19.221920  72.854250       3.0        3.0      1.0   
6252  20000000.0   750.0  19.144320  72.824111       2.0        2.0      0.0   
6253  11000000.0   700.0  19.047201  72.872225       2.0        2.0      0.0   
6254  15000000.0   900.0  19.168818  72.936375       2.0        2.0      0.0   

      parking  Lift  Status_Ready to Move  Status_Under Construction  \
0         0.0   0.0                     0                          1   
1         0.0   0.0                     0                          1   
2         0.0   0.0                     0                          1   
3         2.0   2.0                     1                          0   
4         0.0   0.0                     0                          0   
...       ...   ...                   ...                        ...   
6250      0.0   0.0                     1                          0   
6251      1.0   1.0                     1                          0   
6252      0.0   0.0                     1                          0   
6253      0.0   0.0                     1                          0   
6254      0.0   0.0                     1                          0   

      neworold_New Property  neworold_Resale  Furnished_status_Furnished  \
0                         1                0                           0   
1                         1                0                           0   
2                         1                0                           0   
3                         1                0                           0   
4                         1                0                           0   
...                     ...              ...                         ...   
6250                      0                1                           0   
6251                      0                1                           0   
6252                      0                1                           0   
6253                      0                1                           1   
6254                      0                1                           0   

      Furnished_status_Semi-Furnished  Furnished_status_Unfurnished  \
0                                   0                             0   
1                                   0                             0   
2                                   0                             0   
3                                   0                             0   
4                                   0                             1   
...                               ...                           ...   
6250                                1                             0   
6251                                0                             1   
6252                                0                             0   
6253                                0                             0   
6254                                0                             0   

      type_of_building_Flat  type_of_building_Individual House  
0                         1                                  0  
1                         1                                  0  
2                         1                                  0  
3                         1                                  0  
4                         1                                  0  
...                     ...  

In [3]:

#data = data.fillna(data.mode())
#print(df[['Status', 'Furnished_status']].mode())
#df['Status'] = df['Status']. fillna('Ready to Move')
#df['Furnished_status'] = df['Furnished_status']. fillna('Unfurnished')

print(pd.isnull(df).sum())

price                                0
area                                 0
latitude                             0
longitude                            0
Bedrooms                             0
Bathrooms                            0
Balcony                              0
parking                              0
Lift                                 0
Status_Ready to Move                 0
Status_Under Construction            0
neworold_New Property                0
neworold_Resale                      0
Furnished_status_Furnished           0
Furnished_status_Semi-Furnished      0
Furnished_status_Unfurnished         0
type_of_building_Flat                0
type_of_building_Individual House    0
dtype: int64


In [4]:
y = df["price"]
X = df.drop(["price"], axis=1)
display(y)
display(X)

0       22400000.0
1       35000000.0
2       31700000.0
3       18700000.0
4       13500000.0
           ...    
6250    19500000.0
6251    22000000.0
6252    20000000.0
6253    11000000.0
6254    15000000.0
Name: price, Length: 6255, dtype: float64

area   latitude  longitude  Bedrooms  Bathrooms  Balcony  parking  \
0      629.0  19.032800  72.896357       2.0        2.0      0.0      0.0   
1      974.0  19.032800  72.896357       3.0        2.0      0.0      0.0   
2      968.0  19.085600  72.909277       3.0        3.0      0.0      0.0   
3      629.0  19.155756  72.846862       2.0        2.0      2.0      2.0   
4     1090.0  19.177555  72.849887       2.0        2.0      0.0      0.0   
...      ...        ...        ...       ...        ...      ...      ...   
6250   810.0  19.138320  72.810020       2.0        2.0      0.0      0.0   
6251  1400.0  19.221920  72.854250       3.0        3.0      1.0      1.0   
6252   750.0  19.144320  72.824111       2.0        2.0      0.0      0.0   
6253   700.0  19.047201  72.872225       2.0        2.0      0.0      0.0   
6254   900.0  19.168818  72.936375       2.0        2.0      0.0      0.0   

      Lift  Status_Ready to Move  Status_Under Construction  \
0      0.0                     0                          1   
1      0.0                     0                          1   
2      0.0                     0                          1   
3      2.0                     1                          0   
4      0.0                     0                          0   
...    ...                   ...                        ...   
6250   0.0                     1                          0   
6251   1.0                     1                          0   
6252   0.0                     1                          0   
6253   0.0                     1                          0   
6254   0.0                     1                          0   

      neworold_New Property  neworold_Resale  Furnished_status_Furnished  \
0                         1                0                           0   
1                         1                0                           0   
2                         1                0                           0   
3                         1                0                           0   
4                         1                0                           0   
...                     ...              ...                         ...   
6250                      0                1                           0   
6251                      0                1                           0   
6252                      0                1                           0   
6253                      0                1                           1   
6254                      0                1                           0   

      Furnished_status_Semi-Furnished  Furnished_status_Unfurnished  \
0                                   0                             0   
1                                   0                             0   
2                                   0                             0   
3                                   0                             0   
4                                   0                             1   
...                               ...                           ...   
6250                                1                             0   
6251                                0                             1   
6252                                0                             0   
6253                                0                             0   
6254                                0                             0   

      type_of_building_Flat  type_of_building_Individual House  
0                         1                                  0  
1                         1                                  0  
2                         1                                  0  
3                         1                                  0  
4                         1                                  0  
...                     ...                                ...  
6250                      1                                  0  
6251                      1             

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [6]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((4378, 17), (4378,), (1877, 17), (1877,))

In [7]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge

In [8]:
lr = LinearRegression().fit(X_train, y_train)
for item in zip(X_train.columns, lr.coef_.round()):
    print(item)

lr.predict(X_test)

('area', 22193.0)
('latitude', -79698126.0)
('longitude', -74189229.0)
('Bedrooms', -609342.0)
('Bathrooms', 8534138.0)
('Balcony', -28633.0)
('parking', -28633.0)
('Lift', -28633.0)
('Status_Ready to Move', 2514091.0)
('Status_Under Construction', 4060689.0)
('neworold_New Property', 499450.0)
('neworold_Resale', -499450.0)
('Furnished_status_Furnished', 2480036.0)
('Furnished_status_Semi-Furnished', 171806.0)
('Furnished_status_Unfurnished', -980918.0)
('type_of_building_Flat', 16955.0)
('type_of_building_Individual House', -16955.0)


array([25519225.45616245, -3863600.35193157, 13487391.36180782, ...,
       -6076046.97399426, 49612761.02531624, 24803986.94245815])

In [9]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from math import sqrt

In [10]:
y_pred = lr.predict(X_test)
y_pred

array([25519225.45616245, -3863600.35193157, 13487391.36180782, ...,
       -6076046.97399426, 49612761.02531624, 24803986.94245815])

In [11]:
print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, y_pred))}')
import numpy as np

def MAE(y_test, y_predict):
    return np.sum(abs(np.array(y_test)-np.array(y_predict)))/len(y_test)

def MSE(y_test, y_predict):
    return np.sum((np.array(y_test) - np.array(y_predict))**2) / len(y_test)

def RMSE(y_test, y_predict):
    return sqrt(MSE(y_test, y_predict))

def MAPE(y_test, y_predict):
    return np.mean(abs((np.array(y_test) - np.array(y_predict)) / np.array(y_test)))

def R2(y_test, y_predict):
    return 1 - (MSE(y_test, y_predict) / (np.sum((np.array(y_test) - np.array(y_test).mean())**2) / len(y_test)))
print(f'MAE: {MAE(y_test, y_pred)}')
print(f'MSE: {MSE(y_test, y_pred)}')
print(f'RMSE: {RMSE(y_test, y_pred)}')
print(f'MAPE: {MAPE(y_test, y_pred)}')
print(f'R^2: {R2(y_test, y_pred)}')
print(f'R^2: {lr.score(X_test, y_test)}')

MAE: 8885779.491538448
MSE: 253556398889173.25
RMSE: 15923454.364212975
MAPE: 0.6908425074505005
MAE: 8885779.491538448
MSE: 253556398889173.25
RMSE: 15923454.364212975
MAPE: 0.47726337010049485
R^2: 0.6373484223798138
R^2: 0.6373484223798138


In [12]:
len(lr.coef_)
lr.coef_

array([ 2.21928144e+04, -7.96981264e+07, -7.41892286e+07, -6.09342102e+05,
        8.53413839e+06, -2.86330514e+04, -2.86330514e+04, -2.86330514e+04,
        2.51409088e+06,  4.06068879e+06,  4.99450041e+05, -4.99450041e+05,
        2.48003610e+06,  1.71806363e+05, -9.80917601e+05,  1.69554912e+04,
       -1.69554912e+04])

In [13]:
# L1
ridge = Ridge(alpha=0.06).fit(X_train, y_train)
y_pred = ridge.predict(X_test)
print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, y_pred))}')
print(f'R^2: {ridge.score(X_test, y_test)}')
ridge.coef_

MAE: 8883185.531029865
MSE: 253571929922008.97
RMSE: 15923942.034622237
MAPE: 0.6904769192268658
R^2: 0.6373262089646343


array([ 2.21963562e+04, -7.95927417e+07, -7.38851976e+07, -6.10428463e+05,
        8.53718921e+06, -2.92081530e+04, -2.92081530e+04, -2.92081529e+04,
        2.51263441e+06,  3.82329343e+06,  4.99300536e+05, -4.99300536e+05,
        2.48273103e+06,  1.70378048e+05, -9.83058294e+05,  1.76073961e+04,
       -1.76073961e+04])

In [14]:
# L2
lasso = Lasso(alpha=0.4).fit(X_train, y_train)
y_pred = lasso.predict(X_test)
#print(np.mean(abs(y_test-y_pred)))
print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, y_pred))}')
print(f'R^2: {lasso.score(X_test, y_test)}')
lasso.coef_

MAE: 8885780.007568266
MSE: 253556410773690.88
RMSE: 15923454.737389462
MAPE: 0.6908424022102059
R^2: 0.6373484053818634


array([ 2.21928139e+04, -7.96980911e+07, -7.41891070e+07, -6.09337832e+05,
        8.53413662e+06, -8.58997859e+04, -7.41714132e-11, -5.84711624e-11,
        2.51407569e+06,  4.05892030e+06,  9.98895638e+05, -1.68164866e-09,
        2.48003160e+06,  1.71799885e+05, -9.80921560e+05,  3.39045290e+04,
       -3.64730465e-10])

In [15]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
#import numpy as np

In [16]:
parameters = {'alpha': np.arange(0, 1, 0.1)}
ridge_optimal = GridSearchCV(Ridge(), parameters).fit(X_train, y_train)
ridge_optimal.best_params_

{'alpha': 0.2}

In [17]:
ridge_optimal = RandomizedSearchCV(Ridge(), parameters).fit(X_train, y_train)
ridge_optimal.best_params_

{'alpha': 0.2}

In [18]:
X = X_train.values.reshape(-1,17)
y = y_train.values.reshape(-1,1)

lr = LinearRegression().fit(X, y)
lr.coef_

array([[ 2.21928144e+04, -7.96981264e+07, -7.41892286e+07,
        -6.09342102e+05,  8.53413839e+06, -2.86330514e+04,
        -2.86330514e+04, -2.86330514e+04,  2.51409088e+06,
         4.06068879e+06,  4.99450041e+05, -4.99450041e+05,
         2.48003610e+06,  1.71806363e+05, -9.80917601e+05,
         1.69554912e+04, -1.69554912e+04]])

In [19]:
from sklearn.preprocessing import PolynomialFeatures
# создаем объект, который позволит расширить множество предикторов
pf = PolynomialFeatures(2)
# добавляем новые предикторы
X_p=pf.fit_transform(X) 
X_p

array([[1.00000000e+00, 9.00000000e+02, 1.90327996e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 7.00000000e+02, 1.91110344e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 8.80000000e+02, 1.92143790e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.00000000e+00, 7.50000000e+02, 1.91118958e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 1.40000000e+03, 1.89734119e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 1.14500000e+03, 1.91427505e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [20]:
lr2 = LinearRegression().fit(X_p, y)
lr2.coef_

array([[-3.78206447e+03,  4.38872814e+06, -1.44306718e+10,
        -1.52302430e+10, -9.53550260e+08,  1.37738414e+09,
        -3.97010774e+07, -3.97010780e+07, -3.97010762e+07,
         1.12116398e+09,  4.52497266e+00,  3.12945684e+07,
        -3.12945678e+07,  5.70537257e+08,  5.76093756e+08,
         5.55615070e+08,  4.97343105e+07, -4.97343101e+07,
        -1.06284560e+00, -6.68543913e+04, -1.02737306e+05,
        -1.69058472e+03,  3.77839196e+03,  1.59364036e+02,
         1.58466873e+02,  1.58319488e+02,  3.99349608e+03,
         3.88105556e+03,  2.19311800e+06,  2.19591582e+06,
         1.92675099e+03,  3.02947668e+03, -2.63563485e+03,
         2.19228411e+06,  2.19675468e+06,  1.09569443e+07,
         3.91542619e+08,  3.59289745e+06, -3.13657361e+07,
         1.14199683e+06,  1.14199685e+06,  1.14199686e+06,
        -1.17018849e+07,  7.65181107e+01, -7.21359434e+09,
        -7.21707741e+09, -1.67328567e+07, -1.08277373e+07,
        -4.19344050e+06, -7.21975505e+09, -7.21091670e+0

In [21]:
X_d = X
y_d = lr2.coef_[0][2] + lr2.coef_[0][1]*X_d + lr2.coef_[0][0]*X_d**2
y_d


array([[-1.35442887e+10, -1.43485120e+10, -1.41308469e+10, ...,
        -1.44306718e+10, -1.44262868e+10, -1.44306718e+10],
       [-1.32117737e+10, -1.43481800e+10, -1.41307412e+10, ...,
        -1.44262868e+10, -1.44262868e+10, -1.44306718e+10],
       [-1.34974217e+10, -1.43477414e+10, -1.41309381e+10, ...,
        -1.44306718e+10, -1.44262868e+10, -1.44306718e+10],
       ...,
       [-1.32665369e+10, -1.43481763e+10, -1.41307245e+10, ...,
        -1.44262868e+10, -1.44262868e+10, -1.44306718e+10],
       [-1.56992987e+10, -1.43487641e+10, -1.41311371e+10, ...,
        -1.44306718e+10, -1.44262868e+10, -1.44306718e+10],
       [-1.43639591e+10, -1.43480454e+10, -1.41310506e+10, ...,
        -1.44306718e+10, -1.44262868e+10, -1.44306718e+10]])

In [22]:
y_pred = lr2.predict(X_p)
print(f'R^2: {R2(y, y_pred)}')
y_pred

R^2: 0.77803159909352


array([[17918458.62890625],
       [11340084.67602539],
       [20772137.25      ],
       ...,
       [13876392.11865234],
       [59534859.67285156],
       [24835701.49145508]])

In [23]:
# L1
ridge = Ridge(alpha=0.1).fit(X_p, y)
y_pred = ridge.predict(X_p)
#y_pred = y_d
print(f'MAE: {MAE(y, y_pred)}')
print(f'MSE: {MSE(y, y_pred)}')
print(f'RMSE: {RMSE(y, y_pred)}')
print(f'MAPE: {MAPE(y, y_pred)}')
print(f'R^2: {R2(y, y_pred)}')
#ridge.coef_

MAE: 7591120.389739229
MSE: 187435276585020.6
RMSE: 13690700.368681677
MAPE: 0.3527028342129008
R^2: 0.7688646405017955


D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.40436e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T


In [24]:
# L2
lasso = Lasso(alpha=0.1).fit(X_p, y)
y_pred = lasso.predict(X_p)
print(f'MAE: {MAE(y, y_pred)}')
print(f'MSE: {MSE(y, y_pred)}')
print(f'RMSE: {RMSE(y, y_pred)}')
print(f'MAPE: {MAPE(y, y_pred)}')
print(f'R^2: {R2(y, y_pred)}')
#lasso.coef_

D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.097e+17, tolerance: 3.550e+14
  model = cd_fast.enet_coordinate_descent(


MAE: 101038876745.42136
MSE: 6.068935636416216e+18
RMSE: 2463520983.5550857
MAPE: 1.3772913217584584
R^2: -7482.893350557422
