In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data/regression/mumbai_houses_task.csv')
#data.drop(['Unnamed: 0'], axis=1, inplace=True)
display(df)
s=pd.get_dummies(df)
s.to_csv('data/regression/one-hot_encoded_mumbai_houses_task.csv', index=False)
df = pd.read_csv('data/regression/one-hot_encoded_mumbai_houses_task.csv')
display(df)



price    area   latitude  longitude  Bedrooms  Bathrooms  Balcony  \
0     22400000.0   629.0  19.032800  72.896357       2.0        2.0      0.0   
1     35000000.0   974.0  19.032800  72.896357       3.0        2.0      0.0   
2     31700000.0   968.0  19.085600  72.909277       3.0        3.0      0.0   
3     18700000.0   629.0  19.155756  72.846862       2.0        2.0      2.0   
4     13500000.0  1090.0  19.177555  72.849887       2.0        2.0      0.0   
...          ...     ...        ...        ...       ...        ...      ...   
6250  19500000.0   810.0  19.138320  72.810020       2.0        2.0      0.0   
6251  22000000.0  1400.0  19.221920  72.854250       3.0        3.0      1.0   
6252  20000000.0   750.0  19.144320  72.824111       2.0        2.0      0.0   
6253  11000000.0   700.0  19.047201  72.872225       2.0        2.0      0.0   
6254  15000000.0   900.0  19.168818  72.936375       2.0        2.0      0.0   

                  Status      neworold  parking Furnished_status  Lift  \
0     Under Construction  New Property      0.0              NaN   0.0   
1     Under Construction  New Property      0.0              NaN   0.0   
2     Under Construction  New Property      0.0              NaN   0.0   
3          Ready to Move  New Property      2.0              NaN   2.0   
4                    NaN  New Property      0.0      Unfurnished   0.0   
...                  ...           ...      ...              ...   ...   
6250       Ready to Move        Resale      0.0   Semi-Furnished   0.0   
6251       Ready to Move        Resale      1.0      Unfurnished   1.0   
6252       Ready to Move        Resale      0.0              NaN   0.0   
6253       Ready to Move        Resale      0.0        Furnished   0.0   
6254       Ready to Move        Resale      0.0              NaN   0.0   

     type_of_building  
0                Flat  
1                Flat  
2                Flat  
3                Flat  
4                Flat  
...               ...  
6250             Flat  
6251             Flat  
6252             Flat  
6253             Flat  
6254             Flat  

[6255 rows x 13 columns]

price    area   latitude  longitude  Bedrooms  Bathrooms  Balcony  \
0     22400000.0   629.0  19.032800  72.896357       2.0        2.0      0.0   
1     35000000.0   974.0  19.032800  72.896357       3.0        2.0      0.0   
2     31700000.0   968.0  19.085600  72.909277       3.0        3.0      0.0   
3     18700000.0   629.0  19.155756  72.846862       2.0        2.0      2.0   
4     13500000.0  1090.0  19.177555  72.849887       2.0        2.0      0.0   
...          ...     ...        ...        ...       ...        ...      ...   
6250  19500000.0   810.0  19.138320  72.810020       2.0        2.0      0.0   
6251  22000000.0  1400.0  19.221920  72.854250       3.0        3.0      1.0   
6252  20000000.0   750.0  19.144320  72.824111       2.0        2.0      0.0   
6253  11000000.0   700.0  19.047201  72.872225       2.0        2.0      0.0   
6254  15000000.0   900.0  19.168818  72.936375       2.0        2.0      0.0   

      parking  Lift  Status_Ready to Move  Status_Under Construction  \
0         0.0   0.0                     0                          1   
1         0.0   0.0                     0                          1   
2         0.0   0.0                     0                          1   
3         2.0   2.0                     1                          0   
4         0.0   0.0                     0                          0   
...       ...   ...                   ...                        ...   
6250      0.0   0.0                     1                          0   
6251      1.0   1.0                     1                          0   
6252      0.0   0.0                     1                          0   
6253      0.0   0.0                     1                          0   
6254      0.0   0.0                     1                          0   

      neworold_New Property  neworold_Resale  Furnished_status_Furnished  \
0                         1                0                           0   
1                         1                0                           0   
2                         1                0                           0   
3                         1                0                           0   
4                         1                0                           0   
...                     ...              ...                         ...   
6250                      0                1                           0   
6251                      0                1                           0   
6252                      0                1                           0   
6253                      0                1                           1   
6254                      0                1                           0   

      Furnished_status_Semi-Furnished  Furnished_status_Unfurnished  \
0                                   0                             0   
1                                   0                             0   
2                                   0                             0   
3                                   0                             0   
4                                   0                             1   
...                               ...                           ...   
6250                                1                             0   
6251                                0                             1   
6252                                0                             0   
6253                                0                             0   
6254                                0                             0   

      type_of_building_Flat  type_of_building_Individual House  
0                         1                                  0  
1                         1                                  0  
2                         1                                  0  
3                         1                                  0  
4                         1                                  0  
...                     ...  

In [3]:

#data = data.fillna(data.mode())
#print(df[['Status', 'Furnished_status']].mode())
#df['Status'] = df['Status']. fillna('Ready to Move')
#df['Furnished_status'] = df['Furnished_status']. fillna('Unfurnished')

print(pd.isnull(df).sum())

price                                0
area                                 0
latitude                             0
longitude                            0
Bedrooms                             0
Bathrooms                            0
Balcony                              0
parking                              0
Lift                                 0
Status_Ready to Move                 0
Status_Under Construction            0
neworold_New Property                0
neworold_Resale                      0
Furnished_status_Furnished           0
Furnished_status_Semi-Furnished      0
Furnished_status_Unfurnished         0
type_of_building_Flat                0
type_of_building_Individual House    0
dtype: int64


In [4]:
y = df["price"]
X = df.drop(["price"], axis=1)
display(y)
display(X)


0       22400000.0
1       35000000.0
2       31700000.0
3       18700000.0
4       13500000.0
           ...    
6250    19500000.0
6251    22000000.0
6252    20000000.0
6253    11000000.0
6254    15000000.0
Name: price, Length: 6255, dtype: float64

area   latitude  longitude  Bedrooms  Bathrooms  Balcony  parking  \
0      629.0  19.032800  72.896357       2.0        2.0      0.0      0.0   
1      974.0  19.032800  72.896357       3.0        2.0      0.0      0.0   
2      968.0  19.085600  72.909277       3.0        3.0      0.0      0.0   
3      629.0  19.155756  72.846862       2.0        2.0      2.0      2.0   
4     1090.0  19.177555  72.849887       2.0        2.0      0.0      0.0   
...      ...        ...        ...       ...        ...      ...      ...   
6250   810.0  19.138320  72.810020       2.0        2.0      0.0      0.0   
6251  1400.0  19.221920  72.854250       3.0        3.0      1.0      1.0   
6252   750.0  19.144320  72.824111       2.0        2.0      0.0      0.0   
6253   700.0  19.047201  72.872225       2.0        2.0      0.0      0.0   
6254   900.0  19.168818  72.936375       2.0        2.0      0.0      0.0   

      Lift  Status_Ready to Move  Status_Under Construction  \
0      0.0                     0                          1   
1      0.0                     0                          1   
2      0.0                     0                          1   
3      2.0                     1                          0   
4      0.0                     0                          0   
...    ...                   ...                        ...   
6250   0.0                     1                          0   
6251   1.0                     1                          0   
6252   0.0                     1                          0   
6253   0.0                     1                          0   
6254   0.0                     1                          0   

      neworold_New Property  neworold_Resale  Furnished_status_Furnished  \
0                         1                0                           0   
1                         1                0                           0   
2                         1                0                           0   
3                         1                0                           0   
4                         1                0                           0   
...                     ...              ...                         ...   
6250                      0                1                           0   
6251                      0                1                           0   
6252                      0                1                           0   
6253                      0                1                           1   
6254                      0                1                           0   

      Furnished_status_Semi-Furnished  Furnished_status_Unfurnished  \
0                                   0                             0   
1                                   0                             0   
2                                   0                             0   
3                                   0                             0   
4                                   0                             1   
...                               ...                           ...   
6250                                1                             0   
6251                                0                             1   
6252                                0                             0   
6253                                0                             0   
6254                                0                             0   

      type_of_building_Flat  type_of_building_Individual House  
0                         1                                  0  
1                         1                                  0  
2                         1                                  0  
3                         1                                  0  
4                         1                                  0  
...                     ...                                ...  
6250                      1                                  0  
6251                      1             

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [6]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((4378, 17), (4378,), (1877, 17), (1877,))

In [7]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge

In [8]:
lr = LinearRegression().fit(X_train, y_train)
for item in zip(X_train.columns, lr.coef_.round()):
    print(item)

lr.predict(X_test)

('area', 23487.0)
('latitude', -79616342.0)
('longitude', -73460481.0)
('Bedrooms', 463459.0)
('Bathrooms', 6844822.0)
('Balcony', -35736.0)
('parking', -35736.0)
('Lift', -35736.0)
('Status_Ready to Move', 1592929.0)
('Status_Under Construction', 6611563.0)
('neworold_New Property', 38428.0)
('neworold_Resale', -38428.0)
('Furnished_status_Furnished', 2989218.0)
('Furnished_status_Semi-Furnished', 170200.0)
('Furnished_status_Unfurnished', -558695.0)
('type_of_building_Flat', 203645.0)
('type_of_building_Individual House', -203645.0)


array([18949783.75562096, 16117034.95904064, 18624107.32584476, ...,
       33109590.42647362,  9912313.03807163, 33700854.45353031])

In [9]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from math import sqrt

In [10]:
y_pred = lr.predict(X_test)
y_pred


array([18949783.75562096, 16117034.95904064, 18624107.32584476, ...,
       33109590.42647362,  9912313.03807163, 33700854.45353031])

In [11]:
def MAE(y_test, y_predict):
    return np.sum(abs(y_test-y_predict))/len(y_test)

def MSE(y_test, y_predict):
    return np.sum((y_test - y_predict)**2) / len(y_test)

def RMSE(y_test, y_predict):
    return sqrt(MSE(y_test, y_predict))

def MAPE(y_test, y_predict):
    return np.mean(abs((y_test - y_predict) / y_test))

def R2(y_test, y_predict):
    return 1 - (MSE(y_test, y_predict) / (np.sum((y_test - y_test.mean())**2) / len(y_test)))

In [12]:
print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, y_pred))}')
import numpy as np


print(f'MAE: {MAE(y_test, y_pred)}')
print(f'MSE: {MSE(y_test, y_pred)}')
print(f'RMSE: {RMSE(y_test, y_pred)}')
print(f'MAPE: {MAPE(y_test, y_pred)}')
print(f'R^2: {R2(y_test, y_pred)}')
print(f'R^2: {lr.score(X_test, y_test)}')


MAE: 9301504.987570269
MSE: 266110615380643.88
RMSE: 16312897.209896343
MAPE: 0.7105453689392046
MAE: 9301504.987570269
MSE: 266110615380643.88
RMSE: 16312897.209896343
MAPE: 0.5048747213209503
R^2: 0.6465989157344046
R^2: 0.6465989157344046


In [13]:
len(lr.coef_)
lr.coef_

array([ 2.34869607e+04, -7.96163421e+07, -7.34604805e+07,  4.63459101e+05,
        6.84482171e+06, -3.57364543e+04, -3.57364543e+04, -3.57364543e+04,
        1.59292857e+06,  6.61156264e+06,  3.84278139e+04, -3.84278139e+04,
        2.98921767e+06,  1.70200326e+05, -5.58695175e+05,  2.03644845e+05,
       -2.03644845e+05])

In [14]:
# L1
ridge = Ridge(alpha=0.06).fit(X_train, y_train)
y_pred = ridge.predict(X_test)
print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, y_pred))}')
print(f'R^2: {ridge.score(X_test, y_test)}')
ridge.coef_

MAE: 9298380.241336657
MSE: 266133895607198.56
RMSE: 16313610.747078605
MAPE: 0.7100752682400676
R^2: 0.6465679990522776


array([ 2.34896268e+04, -7.95055868e+07, -7.31390682e+07,  4.63843081e+05,
        6.84771772e+06, -3.63457911e+04, -3.63457911e+04, -3.63457911e+04,
        1.59096781e+06,  6.48001752e+06,  3.85669234e+04, -3.85669234e+04,
        2.99166360e+06,  1.67746432e+05, -5.61545246e+05,  2.04436122e+05,
       -2.04436122e+05])

In [15]:
# L2
lasso = Lasso(alpha=0.4).fit(X_train, y_train)
y_pred = lasso.predict(X_test)
#print(np.mean(abs(y_test-y_pred)))
print(f'MAE: {mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, y_pred))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, y_pred))}')
print(f'R^2: {lasso.score(X_test, y_test)}')
lasso.coef_

MAE: 9301503.71001136
MSE: 266110624342838.34
RMSE: 16312897.48459293
MAPE: 0.7105451841442745
R^2: 0.646598903832402


array([ 2.34869619e+04, -7.96163061e+07, -7.34603511e+07,  4.63459565e+05,
        6.84482162e+06, -1.07210011e+05, -0.00000000e+00, -0.00000000e+00,
        1.59291448e+06,  6.61096631e+06,  7.68513751e+04, -0.00000000e+00,
        2.98921366e+06,  1.70193905e+05, -5.58699030e+05,  4.07283919e+05,
       -0.00000000e+00])

In [16]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
#import numpy as np

In [17]:
parameters = {'alpha': np.arange(0, 1, 0.1)}
ridge_optimal = GridSearchCV(Ridge(), parameters).fit(X_train, y_train)
ridge_optimal.best_params_

D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.95444e-23): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T


{'alpha': 0.2}

In [18]:
ridge_optimal = RandomizedSearchCV(Ridge(), parameters).fit(X_train, y_train)
ridge_optimal.best_params_

D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.95444e-23): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T


{'alpha': 0.2}

In [19]:
X = X_train.values.reshape(-1,17)
y = y_train.values.reshape(-1,1)


X_te = X_test.values.reshape(-1,17)
y_te = y_test.values.reshape(-1,1)


lr = LinearRegression().fit(X, y)

In [20]:
from sklearn.preprocessing import PolynomialFeatures
# создаем объект, который позволит расширить множество предикторов
pf = PolynomialFeatures(2)
# добавляем новые предикторы
X_p=pf.fit_transform(X)

X_p_train = pf.fit_transform(X) 
X_p_test = pf.fit_transform(X_te)

In [21]:
lr2 = LinearRegression().fit(X_p_train, y)

In [23]:
y_pred = lr2.predict(X_p_test)
print(f'R^2: {R2(y_te, y_pred)}')
y_pred

R^2: 0.735855493641159


array([[17372187.14135742],
       [17532131.62255859],
       [14453978.18652344],
       ...,
       [31799775.07495117],
       [15563557.98095703],
       [27848324.17626953]])

In [24]:
parameters = {'alpha': np.arange(0, 1, 0.1)}
ridge_optimal = GridSearchCV(Ridge(), parameters).fit(X_p_train, y)

lasso_optimal = GridSearchCV(Lasso(), parameters).fit(X_p_train, y)

D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.70132e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.98116e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=1.66043e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=2.12629e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rco

D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.104e+17, tolerance: 2.806e+14 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
D:\Work\ML\venv\lib\site-packages\sklearn\model_selection\_validation.py:686: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  estimator.fit(X_train, y_train, **fit_params)
D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_des

D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.446e+17, tolerance: 2.410e+14
  model = cd_fast.enet_coordinate_descent(
D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.034e+17, tolerance: 2.936e+14
  model = cd_fast.enet_coordinate_descent(
D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.167e+17, tolerance: 2.760e+14
  model = cd_f

D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.104e+17, tolerance: 2.806e+14
  model = cd_fast.enet_coordinate_descent(
D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.446e+17, tolerance: 2.410e+14
  model = cd_fast.enet_coordinate_descent(
D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.034e+17, tolerance: 2.936e+14
  model = cd_f

In [36]:
# L1
print(ridge_optimal.best_params_['alpha'])
ridge = Ridge(alpha=ridge_optimal.best_params_['alpha']).fit(X_p_train, y)
y_pred = ridge.predict(X_p_test)
#y_pred = y_d
print(f'MAE: {MAE(y_te, y_pred)}')
print(f'MSE: {MSE(y_te, y_pred)}')
print(f'RMSE: {RMSE(y_te, y_pred)}')
print(f'MAPE: {MAPE(y_te, y_pred)}')
print(f'R^2: {ridge.score(X_p_train, y)}')


#ridge.coef_

0.4
MAE: 7867625.788784091
MSE: 212189384193317.3
RMSE: 14566721.8066838
MAPE: 0.3581755642791549
R^2: 0.7623747289631895


D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=5.8163e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T


In [29]:
# L2
lasso = Lasso(alpha=lasso_optimal.best_params_['alpha']).fit(X_p_train, y)
y_pred = lasso.predict(X_p_test)

print(f'MAE: {MAE(y_te, y_pred)}')
print(f'MSE: {MSE(y_te, y_pred)}')
print(f'RMSE: {RMSE(y_te, y_pred)}')
print(f'MAPE: {MAPE(y_te, y_pred)}')
print(f'R^2: {lasso.score(X_p_train, y)}')




#lasso.coef_

MAE: 42755695651.76644
MSE: 2.4406619472621727e+18
RMSE: 1562261804.9680958
MAPE: 1.344608349028345
R^2: 0.7060387191440364


D:\Work\ML\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.072e+17, tolerance: 3.450e+14
  model = cd_fast.enet_coordinate_descent(


In [ ]:
'''
class LinearRegression:

    def init(self, lr = 0.001, n_iters=1000):
        self.lr = lr
        self.n_iters = n_iters
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(nfeatures)
        self.bias = 0

        for _ in range(self.n_iters):
            y_pred = np.dot(X, self.weights) + self.bias

            dw = (1/n_samples) * np.dot(X.T, (y_pred-y))
            db = (1/n_samples) * np.sum(y_pred-y)

            self.weights = self.weights - self.lr * dw
            self.bias = self.bias - self.lr * db

    def predict(self, X):
        y_pred = np.dot(X, self.weights) + self.bias
        return y_pred
'''

In [ ]:

class RidgeLinearRegression:
    def __init__(self, alpha=1.0):
        self.alpha = alpha

    def fit(self, X, y):
        m, n = X.shape
        X_b = np.c_[np.ones((m, 1)), X]

        # calculate the normal equations with ridge regularization
        A = np.eye(n+1)
        A[0, 0] = 0
        A[1:, 1:] = self.alpha * np.identity(n)
        self.theta = np.linalg.inv(X_b.T.dot(X_b) + A).dot(X_b.T).dot(y)

    def predict(self, X):
        m, n = X.shape
        X_b = np.c_[np.ones((m, 1)), X]
        return X_b.dot(self.theta)

In [ ]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

In [ ]:
model = LinearRegression()
model

y = df["price"]
X = df.drop(["price"], axis=1)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [ ]:
model.fit(X_train, y_train)

#model.predict(X_test)

df = pd.DataFrame(X_train)
df['y'] = y_train
df['pred_fit'] = model.predict(X_test)
df['pred_dot'] = X_train.dot(model.coef_) + model.intercept_
df.head()